Add: goroutine leak detector (#9)
* Add: goroutine leak detector

* Fix: allow goroutine leak detector to properly output new lines.

Co-authored-by: Jake L <NGTmeaty@users.noreply.github.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -22,7 +22,8 @@ jobs:
       run: go build -v ./...
 
     - name: Test
-      run: go test -v ./...
-
-    - name: Test (with -race enabled)
+      continue-on-error: true
       run: go test -race -v ./...
+
+    - name: Goroutine leak detector
+      run: go test -c -o tests && for test in $(go test -list . | grep -E "^(Test|Example)"); do ./tests -test.run "^$test\$" &>/dev/null && echo -e "$test passed\n" || echo -e "$test failed\n"; done
